---
ID: "937c7f78-e037-408a-971b-b71e3de10dc6"
Parent: "c47c030b-0e11-414c-a9c9-33347f8c0f2d"
Template: "c47c030b-0e11-414c-a9c9-33347f8c0f2d"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 960x540 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182943Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c752732a-39e8-4c36-8a28-771ffba93d84"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182943Z
