---
ID: "8fc3bfec-dae9-40ba-82c3-69815a3dd8b3"
Parent: "df7069b9-2f6e-4e44-a983-2d6ee9e362bc"
Template: "df7069b9-2f6e-4e44-a983-2d6ee9e362bc"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Static Hero Text/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190413T221015Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "74eb5fab-66d1-4bc1-ad48-7cc04ec0b8ff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190413T221015Z
