---
ID: "60974628-62f8-4282-8ff3-60976eaab11f"
Parent: "5b764f17-3dac-429b-ab8e-a113f0c6ff59"
Template: "5b764f17-3dac-429b-ab8e-a113f0c6ff59"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Cropped Image Fields/Optional/Image 393x600/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T183140Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ffad2589-ce35-41e2-a55f-51866c1657ff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T183140Z
