---
ID: "85fd9ece-a7f1-4a51-bc8b-f12073447058"
Parent: "2a8117d9-ebd1-430b-abd4-1d33b1fee79c"
Template: "2a8117d9-ebd1-430b-abd4-1d33b1fee79c"
Path: /sitecore/templates/Feature/NOV Com/Modules/Document List/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181027T180757Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63e40a77-3922-4618-bb30-06bf26fddea9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181027T180757Z
