---
ID: "5e22fbdb-6b25-4d6e-ad10-e01e40960bc1"
Parent: "6a2763b2-1500-447e-a40f-c1243bb8e89f"
Template: "6a2763b2-1500-447e-a40f-c1243bb8e89f"
Path: /sitecore/templates/Project/nov/NOV Shared/Rendering Parameters/Slide Wait Time and Autoplay/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181208T214835Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a92714a8-43f3-4d68-949c-e0713432617b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181208T214835Z
