---
ID: "db58518c-3a41-4e02-8833-f956698376dc"
Parent: "c0f52443-15ec-4db9-b95f-87605156f950"
Template: "c0f52443-15ec-4db9-b95f-87605156f950"
Path: /sitecore/templates/Feature/NOV Shared/Item Types/Meta Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150205T224237Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "98e4ddca-5005-4c81-901c-552bf8dbd485"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20150205T224237:635587729578304271Z"
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170605T145204Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6cfc38e1-2c6c-40fd-8f9e-66a346883c6a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170605T145204Z
