---
ID: "a8a151c0-340e-4fa6-a19c-9f270e1beca8"
Parent: "c49d0e23-eda3-4cc5-b753-86fe4e9001fa"
Template: "c49d0e23-eda3-4cc5-b753-86fe4e9001fa"
Path: /sitecore/templates/Feature/NOV Shared/Rendering Parameters/Background Color Param/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "2437c6fb-300e-4e74-b0d2-86a0b95bd678"
      Hint: Background Color
      Value: "{D1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181018T174508Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bd8b42df-0bb2-4d03-85e7-39fab01ecef0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181018T200052Z
