---
ID: "55e57a3e-4f4f-46f4-ab31-a6452eeed905"
Parent: "34de2cc2-1427-4881-abfa-554b2116f88d"
Template: "34de2cc2-1427-4881-abfa-554b2116f88d"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Content Teaser Cards/Content Teaser Card Article/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181207T024023Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "95d93d0e-0954-4c1a-86ab-e2c7c9265138"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181207T024023Z
