---
ID: "0dbb96c9-125c-44c2-b613-d0d5116ba270"
Parent: "c1a40de5-66a2-4012-97cb-0e8007be854c"
Template: "c1a40de5-66a2-4012-97cb-0e8007be854c"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Search Modules/Search Sidebar Section/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181102T190545Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c795fab9-8f42-4329-9262-e5cf01e5055c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190111T120827Z
