---
ID: "c22ffb0a-c9b9-437d-a008-d18969fe6950"
Parent: "6e1cac06-99ee-4297-944a-4af0cb32039a"
Template: "6e1cac06-99ee-4297-944a-4af0cb32039a"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/General Date/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170302T155918Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c0a1c2e2-126a-4f3b-bfe4-1ab3d5f81e68"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170302T155918Z
