---
ID: "b468f278-75ad-468d-88c7-91b7e418844b"
Parent: "15376d8c-5898-420e-8b88-c66e335298a2"
Template: "15376d8c-5898-420e-8b88-c66e335298a2"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Show Static Background Image/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181222T172050Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "44553895-e394-4de0-902f-4fdbfe0db1eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181222T172050Z
