---
ID: "ba009618-31d4-4fa3-b597-77b5a2b75306"
Parent: "abe95439-efc4-46b2-9ee9-45266175c1b3"
Template: "abe95439-efc4-46b2-9ee9-45266175c1b3"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Search Modules/Sidebar Section Download/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181102T221246Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b5d45ce0-834c-4766-9fd1-d46553db45d6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190122T215924Z
