---
ID: "240f35b2-039b-4b7c-81e9-80288431a2ee"
Parent: "b13f2af7-8681-4b7c-9bf7-7b8d3ec2c4a8"
Template: "b13f2af7-8681-4b7c-9bf7-7b8d3ec2c4a8"
Path: /sitecore/templates/Project/nov/NOV Com/Item Types/Search Page/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{40C0E7ED-9887-49E1-8E89-43D16DD2AD6C}">
        <r
          ds=""
          id="{639E8A97-3CB0-427A-886C-47EA52AC2839}"
          par="Number_Of_Items_Per_Page=20&amp;Top_Margin"
          ph="main"
          uid="{E83429AA-FAA8-4492-B43C-4EAC45D06B61}" />
      </d>
    </r>
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T202626Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eccbe8e3-6f4b-4c92-8cbb-e52cef38a369"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190123T011617Z
