---
ID: "b44c80db-a392-48b2-acfa-70089b79c578"
Parent: "7ec80421-5b7c-44c5-88a0-551cca5a7bdb"
Template: "7ec80421-5b7c-44c5-88a0-551cca5a7bdb"
Path: /sitecore/templates/Feature/NOV Com/Modules/Slide/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T173456Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e17ac0d5-f51c-47bd-a4d8-2e4a65b2ecba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181023T173456Z
