---
ID: "ff9c522d-e3ba-408a-8cbd-4e493528203f"
Parent: "8ea745c3-c333-4d50-b246-e302e50f69ef"
Template: "8ea745c3-c333-4d50-b246-e302e50f69ef"
Path: /sitecore/templates/Feature/NOV Shared/Components/Eloqua Forms Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{7102FC69-5D90-4423-A8DF-327E6D263D95}"
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181030T192335Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d75a9091-11d5-4740-a2aa-c4063922e171"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181030T192436Z
