---
ID: "79c8f441-4e17-4427-a433-b180ef7d5d56"
Parent: "d4154973-293e-4360-be0d-c8989c2a18f4"
Template: "d4154973-293e-4360-be0d-c8989c2a18f4"
Path: /sitecore/templates/Feature/NOV Shared/Rendering Parameters/Margin/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170405T193632Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "25425278-b769-4769-8304-5236570f0e6c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170405T193938Z
