---
ID: "a45c99e0-02ea-4741-bdce-21927c52f6a1"
Parent: "a42be250-5aa9-4984-a08b-0a88e538acc0"
Template: "a42be250-5aa9-4984-a08b-0a88e538acc0"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Hover Image/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181021T185615Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "900fe1f2-80bd-4b14-aedc-46c7b3f9cd52"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181021T185615Z
