---
ID: "a34c8fcb-789a-4a55-b1b8-ea673fe048fe"
Parent: "93bfcce6-2e73-4efa-a13f-8c1e3faf3850"
Template: "93bfcce6-2e73-4efa-a13f-8c1e3faf3850"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Product/Brand Capability List/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181115T183457Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "da65f160-9af0-441d-a852-676bc42398af"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190312T220051Z
