---
ID: "a1843cac-0f70-48da-9fe8-929e6b177bcb"
Parent: "1fff4718-e8e9-48b6-bff7-b4be32fc9586"
Template: "1fff4718-e8e9-48b6-bff7-b4be32fc9586"
Path: /sitecore/templates/Project/nov/NOV Shared/Components/Brand/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181207T025502Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3d01842-d5fe-493e-bbf1-48531373637e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181207T025502Z
