---
ID: "44703b68-4456-4120-b3b0-a738a06448e0"
Parent: "e1d6e91c-2f9e-4b2d-9705-9bff59af35f9"
Template: "e1d6e91c-2f9e-4b2d-9705-9bff59af35f9"
Path: /sitecore/templates/Feature/NOV Com/Modules/Cards/Flip Cards/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180921T165837Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "768fa4c8-f8cf-499d-93e8-c1c1ef397202"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180921T165837Z
