---
ID: "3488ef97-3099-47c7-b7a2-1426039e905d"
Parent: "2e17b03e-c459-4bb0-b9d9-0acc1c118c54"
Template: "2e17b03e-c459-4bb0-b9d9-0acc1c118c54"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 514x295 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182711Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "90f820df-240d-4cfd-8195-fa8d58a82fd8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182711Z
