---
ID: "6d1a8a2c-aa21-49b9-a296-eb3a6cb8bd27"
Parent: "800ef4cb-3273-4756-ad58-fd9b119e02bf"
Template: "800ef4cb-3273-4756-ad58-fd9b119e02bf"
Path: /sitecore/templates/Project/nov/NOV Com/Item Types/Card List Page/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/id_cards.png
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      xmlnxsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{40C0E7ED-9887-49E1-8E89-43D16DD2AD6C}">
        <r
          ds=""
          id="{FA28682B-1CF3-426A-BE1B-F359A64D6282}"
          par="Add Gradient=1&amp;Text Color=white"
          ph="/main/hero-slide-{891379C9-C5B8-43EF-9A11-3157D7259FBC}-0"
          uid="{29CCFEC8-7728-4642-A74C-DBB3C36E5A66}" />
        <r
          id="{AB213187-9551-4F9B-AE3D-261BB2B2434F}"
          ph="main"
          uid="{891379C9-C5B8-43EF-9A11-3157D7259FBC}" />
        <r
          ds="{274BB447-32EB-4791-B569-3F2E71225931}"
          id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
          par="Alignment"
          ph="main"
          uid="{567B5EE0-2011-441D-99C4-B048296EF03C}" />
        <r
          ds="{A225D403-64C1-4B22-BF83-5706576E5276}"
          id="{93ADFF97-73E8-46AA-9C18-068BDB6232A8}"
          par=""
          ph="main"
          uid="{29C0FB27-9EBE-466C-9648-1B3CED591D78}" />
        <r
          ds="{38C532DB-5D85-4A34-84A2-CFF991EA17AE}"
          id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
          par="Alignment=left&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
          ph="main"
          uid="{55E55775-15F4-4BFC-8652-856E7AD1B9BA}" />
        <r
          ds="{38C532DB-5D85-4A34-84A2-CFF991EA17AE}"
          id="{8F62822C-3DD6-40BE-B167-850DE5BBE38B}"
          par="Alignment=right&amp;Background Color=%7BD1DB5F29-9D9E-4EC0-B651-0EEBFDC1AEB5%7D"
          ph="main"
          uid="{ADEFD730-6D25-41BA-B761-A852AA7DFCC1}" />
        <r
          ds="{36B70B95-7C53-44B8-9F6F-99297D8A9F38}"
          id="{410308FD-D76D-48D4-9E14-E9C56F2AECDF}"
          par=""
          ph="main"
          uid="{5287F413-D547-4F9D-8A6B-98CCCA8F16C3}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180918T212807Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fbc8eb5d-32aa-4fe5-bc13-5ed6b648791d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230706T170916Z
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180919T140957Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: $name
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "52f14c5c-1f92-454c-8919-b4795666314c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "bcfd3e35-8ec5-4ba4-b22f-00669ef4d2d5"
      Hint: Publish Date
      Value: 20181015T000000Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220505T200731Z
