---
ID: "436bcf2a-6c0f-4634-a159-3a2b880f5dbc"
Parent: "2659cddc-79d0-4767-8a68-fbd97433c99c"
Template: "2659cddc-79d0-4767-8a68-fbd97433c99c"
Path: /sitecore/templates/Feature/NOV Com/Modules/Product/Product Tab/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181102T143031Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ffaee96f-68c1-4f2c-9256-0739be0cc650"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181218T192540Z
