---
ID: "6a58861a-6db4-4bde-bf26-1d2cd3d182c3"
Parent: "40f30794-0164-488f-9fad-e77c07a645dd"
Template: "40f30794-0164-488f-9fad-e77c07a645dd"
Path: /sitecore/templates/Feature/NOV Com/Modules/Z1 Custom Code Injector/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211123T133533Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3d649d3c-8cc2-438a-a82e-86b3ab71e359"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211123T133533Z
