---
ID: "4367678c-1028-4b1b-9456-f1033ebf789e"
Parent: "d5c68f49-2145-4214-b1e0-ab2974f39b85"
Template: "d5c68f49-2145-4214-b1e0-ab2974f39b85"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Image Blocks/Image Video Block 960x1080/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181208T232402Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3e666a73-2b15-4579-94a5-f438c4db19a4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181208T234243Z
