---
ID: "6aaf36c6-14bd-49bd-a258-95ac83d6c796"
Parent: "6fad82ca-252c-458f-9f63-55e7b6216d46"
Template: "6fad82ca-252c-458f-9f63-55e7b6216d46"
Path: /sitecore/templates/Feature/NOV Com/Modules/FAQ Accordion Item/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181207T024151Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4056008a-a7f1-44df-bd82-a82565ceb34a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181207T024151Z
