---
ID: "ee3324b2-1583-4269-9f86-5571afe3317d"
Parent: "7f8ac609-214e-47f5-9e9d-1618ae75b560"
Template: "7f8ac609-214e-47f5-9e9d-1618ae75b560"
Path: /sitecore/templates/Feature/NOV Com/Modules/Content Teaser Cards/Content Teaser Card News/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181207T024039Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "69b21e37-a12a-4ac5-9536-19b670373326"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181207T024039Z
