---
ID: "6641c7e3-d7aa-4332-8f32-9401d0433645"
Parent: "5cf4c398-c248-4e85-aba6-a912f9d972ae"
Template: "5cf4c398-c248-4e85-aba6-a912f9d972ae"
Path: /sitecore/templates/Feature/NOV Com/Components/System/Content Tag/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170317T135533Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a7806896-40c7-4140-96ac-eda42fde2267"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170317T135533Z
