---
ID: "70085cc5-2d6c-46aa-a850-d622a1fa0b32"
Parent: "9d895f63-b5d6-4826-94f2-8b9881e36426"
Template: "9d895f63-b5d6-4826-94f2-8b9881e36426"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Content Tag Optional/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181004T144315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bd2e1a98-3adc-4c01-b0bf-ba4c7b73d77c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181004T144315Z
