---
ID: "ea9526d2-03ca-457a-91c1-3791ca013a73"
Parent: "9b86cf5e-fa4b-413e-8ee4-9d2ac83e6e62"
Template: "9b86cf5e-fa4b-413e-8ee4-9d2ac83e6e62"
Path: /sitecore/templates/Feature/NOV Shared/Rendering Parameters/Center Text/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "21c27505-096a-4bcb-933f-bab3687064ae"
      Hint: Enable Center Text
      Value: true
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181208T214316Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8c6fdcd6-d9b3-4ed0-891f-a7d5f438fcf8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190926T154606Z
