---
ID: "d3e05c03-9e4e-4921-8155-a8daff87ac51"
Parent: "5c70ee4b-1d66-41d1-a671-1cd882733bf5"
Template: "5c70ee4b-1d66-41d1-a671-1cd882733bf5"
Path: /sitecore/templates/Feature/NOV Com/Modules/Hero Modules/Product Hero/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181116T192325Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9178cd30-e848-468c-8cd7-ce185f097faa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181222T171143Z
