---
ID: "e00fd30a-97ed-4e3e-be80-051c21a5d6ae"
Parent: "f96f5c5e-9e6f-4ee1-90c6-70a25f724cb7"
Template: "f96f5c5e-9e6f-4ee1-90c6-70a25f724cb7"
Path: /sitecore/templates/Feature/NOV Com/Modules/Filtered Feed/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "1055e71c-db1c-4851-851c-eb6f3e46afb3"
      Hint: maxNumberofItems
      Value: 20
    - ID: "2309835a-4a1e-4d72-ad50-a2386d026443"
      Hint: initialItemCount
      Value: 6
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181005T192349Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "7a5a3c53-83a1-428a-aec7-c8b19094bad1"
      Hint: noCardsText
      Value: No pages to display based on the current filters
    - ID: "7a7ed74a-154b-4c3a-b8cf-deb48cd5913d"
      Hint: sortBy
      Value: date
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e184e5fb-f26f-4a14-88a5-27cc59119625"
    - ID: "90db8228-6c8b-4678-809c-1c6a6e083d8f"
      Hint: filterByText
      Value: Filter By
    - ID: "93499c7b-da90-4c4f-9d7f-26324aaad89e"
      Hint: learnMoreText
      Value: Learn More
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d0318cf7-e513-476d-955a-ea54d12cdee2"
      Hint: resetFilterText
      Value: Reset Filters
    - ID: "d5da8994-7cab-4bc2-8feb-43f8402c5e8d"
      Hint: loadMoreItemsCount
      Value: 6
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190111T052928Z
    - ID: "f88ca97c-8bbb-4012-b42d-9d04c31ba823"
      Hint: sortOrder
      Value: desc
    - ID: "fbbbc862-f1c0-4f81-89b4-2ca6549fc246"
      Hint: loadMoreText
      Value: Load More
