---
ID: "4dcccab3-9486-4772-8789-dc1cf98938fe"
Parent: "f01f683a-767b-4ac4-8ebc-04b38472a649"
Template: "f01f683a-767b-4ac4-8ebc-04b38472a649"
Path: /sitecore/templates/Project/nov/NOV Com/Item Types/Globals/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{569AFDF0-3638-43A2-8A58-C569799C1BF7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150205T215717Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5e5820e1-ffd5-4e14-bee3-e0fe8230f687"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20150206T212053:635588544534035043Z"
