---
ID: "da743208-a555-49bf-a51f-550f1f46955f"
Parent: "1954d3be-9277-4530-ba89-5c5eaad52cd9"
Template: "1954d3be-9277-4530-ba89-5c5eaad52cd9"
Path: /sitecore/templates/Feature/NOV Shared/Modules/Base/Module Optional Text/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T163900Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "080ad8b2-3d00-495c-b3a4-b78f28e2e350"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170227T163900Z
