---
ID: "49882ef1-f701-4b86-ad1c-5c2bbd92b539"
Parent: "5cadf085-a6fa-4b87-9768-b895e5745b16"
Template: "5cadf085-a6fa-4b87-9768-b895e5745b16"
Path: /sitecore/templates/Project/nov/NOV Shared/Rendering Parameters/Title Block Alignment/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180921T182216Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "859900c8-7e93-49d2-998c-693cbfe14761"
      Hint: Alignment
      Value: center
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6a1e5a35-b430-4cec-9b20-aaaf8c3f6748"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190123T185217Z
