---
ID: "baca1cd3-c198-483f-86b8-aa0e984d6327"
Parent: "f1dd3a92-11da-48fd-8c6b-a1a776e58435"
Template: "f1dd3a92-11da-48fd-8c6b-a1a776e58435"
Path: /sitecore/templates/Project/nov/NOV Com/Modules/Content List 3x1/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181022T182945Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c6e07f46-39c9-4e7d-83ed-5c03e7a4f6b4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181023T134724Z
