---
ID: "8a875eb0-88b5-49dd-99a7-88d3a8dc81ac"
Parent: "0fbf557d-b9fc-401e-a796-d4da049db55b"
Template: "0fbf557d-b9fc-401e-a796-d4da049db55b"
Path: /sitecore/templates/Project/nov/NOV Shared/Modules/Base/Module Link/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170317T180543Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1789ad6c-9629-479e-8d2e-9831b0a41c96"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170317T180543Z
