---
ID: "df665131-bb34-46f2-86c3-5a35aefa8f31"
Parent: "dbc23d7d-62bd-46a5-b584-58b43c5dfaad"
Template: "dbc23d7d-62bd-46a5-b584-58b43c5dfaad"
Path: /sitecore/templates/Project/nov/Item Types/Redirect Page/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{713C10EA-CD06-403B-84AB-FFDCAF30AD8E}">
        <r
          id="{E1559D06-D62A-45EB-9524-B333BA48D892}"
          ph="main"
          uid="{B03AA8C7-EFFC-4BBF-BCF5-E58789DC1F75}" />
      </d>
    </r>
Languages:
- Language: "en-us"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180927T184422Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4e71d45b-5f6e-4a86-8af7-a7d8f769dc57"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190416T202633Z
