---
ID: "e247df7c-92eb-472b-a8a9-ae6c4762be58"
Parent: "82b2985d-c176-4252-8d59-780e0aaf0038"
Template: "82b2985d-c176-4252-8d59-780e0aaf0038"
Path: /sitecore/templates/Project/nov/NOV Com/Field Sections/Header/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "007fb71d-d96e-4e90-a4c1-1e52149fa8fb"
      Hint: liveChatWithUs
      Value: Chat with Us
    - ID: "0e7bb884-f3c2-48e5-8f80-759cfc15f5bc"
      Hint: loginLinks
      Value: 
    - ID: "1ae1fd0c-409d-4d0f-8abd-d5307bf3ad9b"
      Hint: loginLinksMobileMenuTitle
      Value: Login
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170316T141309Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "70ca41ce-9092-4fa9-a529-86189c9e3d8e"
      Hint: contactUsMobileMenuTitle
      Value: Contact us
    - ID: "72006364-a9e9-4078-acfe-6c2b9eb2696d"
      Hint: languageSites
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a9346f74-3d6d-42c2-afab-1282758e18f2"
    - ID: "90e624ba-7656-4ad0-9df9-29fcb185052e"
      Hint: loginLinksMenuTitle
      Value: Login
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180911T205000Z
