---
ID: "3a789dfb-1507-40f4-9d17-e34dd8d5ccde"
Parent: "a2931cae-c10e-400e-b85e-143cad8ac8e8"
Template: "a2931cae-c10e-400e-b85e-143cad8ac8e8"
Path: /sitecore/templates/Project/nov/NOV Shared/Rendering Parameters/Product Hero Options/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190325T212010Z
    - ID: "861593d6-f27e-4025-8e2e-86357b1c6d63"
      Hint: Add Gradient
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7da13d6c-0e20-4ff5-9729-685b8535433c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190523T151349Z
