---
ID: "453bfd67-4bf9-4a2b-957a-36c7bc72d72e"
Parent: "9c2677bb-7840-4e59-ac44-4c5d4dff7610"
Template: "9c2677bb-7840-4e59-ac44-4c5d4dff7610"
Path: /sitecore/templates/Project/nov/NOV Com/Item Types/Business Segment Page/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{40C0E7ED-9887-49E1-8E89-43D16DD2AD6C}">
        <r
          ds=""
          id="{FA28682B-1CF3-426A-BE1B-F359A64D6282}"
          par="Add Gradient=1&amp;Text Color=white"
          ph="/main/hero-slide-{3709ECF8-31A3-4630-B462-DC1F06EEF338}-0"
          uid="{82C814F0-E3F8-47FE-A4C3-6765E3B4DF94}" />
        <r
          id="{AB213187-9551-4F9B-AE3D-261BB2B2434F}"
          ph="main"
          uid="{3709ECF8-31A3-4630-B462-DC1F06EEF338}" />
        <r
          ds="{274BB447-32EB-4791-B569-3F2E71225931}"
          id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
          par="Alignment"
          ph="main"
          uid="{28B4ABC6-0A05-401D-8D9F-70992A0772FB}" />
        <r
          ds="{E9BD5683-072B-4C57-9CE0-BF4C8F5C3C36}"
          id="{7EE99E6C-C671-468E-8381-C6B9BB1E6416}"
          par=""
          ph="main"
          uid="{0D57F642-56E7-4087-9356-C56DCEA3F091}" />
        <r
          ds="{274BB447-32EB-4791-B569-3F2E71225931}"
          id="{EAEFE2D3-091C-438E-9B07-903F732D1754}"
          par="Alignment"
          ph="main"
          uid="{85AC0D69-6C39-4691-8D47-A8000B6EA60A}" />
        <r
          ds="{DEA7CE43-D717-4956-82B9-95E9E7361FA9}"
          id="{09A5B06F-A291-4BC8-8851-CC3FBB8D885D}"
          par=""
          ph="main"
          uid="{606DBDA0-AAFF-447A-B2F8-5433CB8107B8}" />
        <r
          ds="{4E1FB948-29CC-43BA-A9A4-400222C28D3E}"
          id="{404FE8DE-C601-4E14-8D3D-32F27B41D06D}"
          par=""
          ph="main"
          uid="{F7113DE4-6D33-4768-B510-981B8992BF48}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180919T132745Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "990cadc8-e85c-4056-a3a7-498f5f2ea42c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230706T170915Z
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1e6decbd-039c-43cc-b439-0a198f868334"
      Hint: Featured Story Headline
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180919T141016Z
    - ID: "3a81e0b8-4742-4d96-be89-8c1f3716c285"
      Hint: Mobile Menu Title
      Value: $name
    - ID: "5175483b-161a-4999-9f30-34be82e2d85b"
      Hint: Page Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "6d59e31a-53a8-41a5-9e9f-31362a416be7"
      Hint: Menu Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f567648d-5f80-4259-a0a9-728616b81d21"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "bcfd3e35-8ec5-4ba4-b22f-00669ef4d2d5"
      Hint: Publish Date
      Value: 20181015T000000Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220505T200602Z
