---
ID: "f5945a84-3788-4e23-ba27-e39b43d4bb1b"
Parent: "33e8c668-c9ed-4e14-a482-b37830d27432"
Template: "33e8c668-c9ed-4e14-a482-b37830d27432"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Content Tag Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181004T144742Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3129dab2-b1f8-44ee-8a80-481ac4483aee"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181004T144742Z
