---
ID: "d160983c-e5b1-4445-b8f7-368d35e1b64c"
Parent: "a8a3be14-3024-4a01-953f-89800c31bd71"
Template: "a8a3be14-3024-4a01-953f-89800c31bd71"
Path: /sitecore/templates/Project/nov/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 96x96 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182948Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9763b913-66f2-48a8-a82f-d0f273488042"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182948Z
