---
ID: "d412d002-9fcb-4924-a876-fc19389fb0ef"
Parent: "21527b3e-461e-4fa3-913d-f9828b76ac18"
Template: "21527b3e-461e-4fa3-913d-f9828b76ac18"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Standard Text/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170306T200757Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a9aaabdb-c349-4cae-9bc0-5354896a8154"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170306T200757Z
