---
ID: "3ae23418-92ef-4bf8-9438-5cb309e633ac"
Parent: "f7e21fcc-e544-4835-a423-1c4b48a02b5f"
Template: "f7e21fcc-e544-4835-a423-1c4b48a02b5f"
Path: /sitecore/templates/Project/nov/NOV Shared/Rendering Parameters/Link Type/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181208T213906Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ashwin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ashwin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38b6475c-bf5f-4ba4-9d77-d343af99a0e8"
    - ID: "953e5bbf-af9b-42c7-a7bf-18e3fed52c41"
      Hint: Use Button for Link
      Value: link
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190610T170647Z
