---
ID: "c73f721c-bc25-46d1-abad-2301b2f50ea0"
Parent: "d3c5ba1a-7fa1-4676-ad56-f6ea84300a3f"
Template: "d3c5ba1a-7fa1-4676-ad56-f6ea84300a3f"
Path: /sitecore/templates/Feature/NOV Com/Components/Search/Search Category/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{826ED626-398D-493E-9CB3-E9C21CFF5932}" />
    </r>
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170426T201229Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a3ec1daf-e002-4087-a35c-2091010daa61"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ashwin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20181102T184555Z
    - ID: "f28719a1-3418-4255-b166-0494393733b7"
      Hint: categoryName
      Value: $name
