---
ID: "ff457a08-2d19-473e-848b-58b25fc5d967"
Parent: "9d80a2eb-9d73-4a9e-ad33-04dd6ef7ac7d"
Template: "9d80a2eb-9d73-4a9e-ad33-04dd6ef7ac7d"
Path: /sitecore/templates/Feature/NOV Shared/Modules/Base/Module Personalization Segments/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170914T191834Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "19b7911c-b02e-41d8-b4b8-b8e7fbd09e07"
    - ID: "9f184a79-cbf7-44ac-9cd6-7c5bf11f0b4f"
      Hint: Segments
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170914T203406Z
