---
ID: "917fe356-6825-41ef-8e03-e073de4d6c76"
Parent: "518db51f-e02a-42fa-bf16-96db0f1b29f0"
Template: "518db51f-e02a-42fa-bf16-96db0f1b29f0"
Path: /sitecore/templates/Feature/NOV Shared/Field Sections/Cropped Image Fields/Required/Image 640x1080 Required/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T182717Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e0baf447-05a2-4dc4-baf8-c941c0909504"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190121T182717Z
