---
ID: "61711ea7-1cf1-4b78-98a9-3039dadd387f"
Parent: "03ee4960-81a8-450f-98f4-08ac9a5a3ab8"
Template: "03ee4960-81a8-450f-98f4-08ac9a5a3ab8"
Path: /sitecore/templates/Project/nov/NOV Shared/Modules/Base/Module Headline/__Standard Values
Languages:
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T163903Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "79b9b64d-fa7d-4d7a-b06e-29aa34867591"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170227T163903Z
